apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-01-25T15:19:55Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "778434"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: 59a6044e-00e5-409a-890b-694429cfa768
spec:
  clusterIP: 10.97.85.94
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32606
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
